### ISSUE TITLE
Initial Template doesn't show debug menus for contracts

### ISSUE THREAD

**Issue by vanities** [scaffold-eth/scaffold-eth-typescript#101]
**Describe the bug**

**To Reproduce**
1. Go to [the repo](https://github.com/scaffold-eth/scaffold-eth-typescript)
2. Click on Use this Template
3. Clone the repo in a folder
4. run `yarn chain`, then `yarn contracts:build && yarn deploy` then `yarn start`
5. See error below for **NFT** tab and **Your Contract**

**Expected behavior**
The debugging interface should be there

**Screenshots**
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/9370260/178114101-866fcdb0-b4a2-483d-bb96-ee33d2dd2d3f.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Brave
 - Version  v1.40.113 

**Additional context**

**Comment by ShravanSunder** [comment]
its working fine for me.  please provide a reproduction

i would also use yarn contracts:rebuild to make sure everything is cleaned and built again

**Comment by ShravanSunder** [comment]
i would also use yarn contracts:rebuild to make sure everything is cleaned and built again

**Comment by ShravanSunder** [comment]
no response
