### ISSUE TITLE
useBalance / useContractReader not updating on new block number in next app

### ISSUE THREAD

**Issue by elenamik** [scaffold-eth/scaffold-eth-typescript#106]
**Describe the bug**
The useBalance & useContractReader hooks are not updating on new block numbers, even though the docs say they should be. 

**To Reproduce**
1. Clone the template
2. Start up the nextjs app
3. Send faucet eth to a wallet
4. The balance will not change, but if you refresh it updates

**Expected behavior**
useBalance and useContractReader should update on block number change.

**Screenshots**
https://youtu.be/yh_6pEX-dp0

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] chrome

**Comment by ShravanSunder** [comment]
- related to https://github.com/scaffold-eth/eth-hooks/issues/229
