### ISSUE TITLE
does not work with surge out of the box (process.env not defined) (neither vite nor nextjs)

### ISSUE THREAD

**Issue by msmyers** [scaffold-eth/scaffold-eth-typescript#112]
**Describe the bug**
 * when deploying on surge, 
   - the vite build (when viewed on surge) throws an error that "process" is not defined.
   - the next build (when viewed on surge) throws 404 not found.

**To Reproduce**

`yarn build && yarn surge`

**Expected behavior**
I expected the website to load.

**Screenshots**

---

Fix:

 * nextjs
   - Modify `nextjs-app-ts/package.json` to say `"build": "yarn build:anttheme && next build && next export -o dist",` (add "`export -o dist`")
   - Add `    "surge": "yarn surge dist",`

* vite
  -  https://github.com/vitejs/vite/pull/8090 (whackamole strategy)
  - https://github.com/vitejs/vite/issues/1973
  - https://github.com/vitejs/vite/issues/161

```
// see https://vitejs.dev/config/shared-options.html#define
define: {
  'process.env.SOME_ENV': `"${process.env.SOME_ENV}"`
}
```

```
// see: https://www.npmjs.com/package/vite-plugin-environment
import { defineConfig } from 'vite'

export default defineConfig({
  define: {
    'process.env.API_KEY': JSON.stringify(process.env.API_KEY),
    'process.env.DEBUG': JSON.stringify(process.env.DEBUG),
  }
})
```

**Comment by ShravanSunder** [comment]
To be fixed  in new version.  
@msmyers the nextjs version won't be chaned.  It doesn't make sense to use nextjs for static build when you can use the vite version.
