### ISSUE TITLE
ethers.getContract is not a function

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-typescript#114]
**Describe the bug**
I was trying to deploy a contract with `hardhat-deploy` and got this error `ethers.getContract ` is not a function. Although we wrapped `hardhat-deploy-ethers` in `package.json` still its giving me this error.

**Screenshots**
![Screenshot 2022-08-25 at 3 40 15 PM](https://user-images.githubusercontent.com/80153681/186638441-97ac4072-75f2-4a45-9282-f98bd20d9217.jpg)

**Comment by technophile-04** [comment]
@ShravanSunder could you please help me with this...I tried `yarn add @nomiclabs/hardhat-ethers@npm:hardhat-deploy-ethers ethers` again inside `packages/hardhat-ts` and also made sure `import '@nomiclabs/hardhat-ethers'` is present in 
`hardhat.config.ts` also this solution/references I tired : 
- https://github.com/wighawag/hardhat-deploy-ethers/issues/12#issuecomment-915591370
-  https://github.com/Tenderly/hardhat-tenderly/issues/51#issuecomment-1199129116

**Comment by paOol** [comment]
+1,

ran into this issue a bunch of times as well.

**Comment by ShravanSunder** [comment]
@technophile-04 are you using the base release branch without any changes?

**Comment by technophile-04** [comment]
Yes using the release branch

**Comment by ShravanSunder** [comment]
@technophile-04 did you run `yarn compile` first?  

I'm also releasing a larger `next` branch change into `release` soon so that might help as well.

**Comment by technophile-04** [comment]
Eagerly Waiting for new changes  @ShravanSunder  🤩!.... Yes first I ran `yarn contracts:build` and then `yarn deploy` but not working. I tried tinkering to get it worked by migrating to  [hardhat-toolbox](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-toolbox) instead. But don't know if I migrated it correctly :(. 

Thanks so much for maintaining this repo 🙏.

**Comment by ShravanSunder** [comment]
@technophile-04 i just merged the new version, it has a CLI and is slightly different.   Checkout the readme for more info.

It should be updated to hardhat-toolbox as well.  Here's a video overview:  https://www.youtube.com/watch?v=bEd6wV2H28g

**Comment by technophile-04** [comment]
Just tried it out and it's fixed now 🤩... Thanks so much @ShravanSunder  !
