### ISSUE TITLE
`subgraph` commands not found 

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/scaffold-eth-typescript#117]
There are many `subgraph` commands of `scaffold-eth` that are not compatible with this repository. The commands in this [README.MD](https://github.com/scaffold-eth/scaffold-eth-typescript/tree/release/packages/advanced/subgraph#readme) also are not in line with scripts. I tried fixing it but was not able to wrap my head around the architecture. Would love some help

**Comment by ShravanSunder** [comment]
@technophile-04 this is in the mist of changing.  You'll need to cd into the subgraph folder and then try to run the commands

the subgraph readme file should be updated, it'd be great if you want to create a PR.

**Comment by technophile-04** [comment]
Yup will work on that need to wrap my head around it 😅🙌

**Comment by ShravanSunder** [comment]
@technophile-04  thank you, i'll merge the commit
