### ISSUE TITLE
tailwind.config.cjs has wrong content path

### ISSUE THREAD

**Issue by oxdog** [scaffold-eth/scaffold-eth-typescript#118]
The config has a wrong path and causes tailwindcss to not work.

https://github.com/scaffold-eth/scaffold-eth-typescript/blob/5bc21ee7c3291739f7de7a6838a640c72b016213/packages/nextjs-app-ts/tailwind.config.cjs#L2

It should be 
  `content: ['./index.html', './src/pages/**/*.{vue,js,ts,jsx,tsx}', './src/components/**/*.{vue,js,ts,jsx,tsx}'],`

**Comment by ShravanSunder** [comment]
@oxdog  thanks will update!

**Comment by ShravanSunder** [comment]
the new version of release/next branches should have this now
