### ISSUE TITLE
Internal Server Error when running production build

### ISSUE THREAD

**Issue by polats** [scaffold-eth/scaffold-eth-typescript#128]
**Describe the bug**

An Internal Server Error occurs when running a production build. The console errors out with `TypeError: jsxDevRuntime.jsxDEV is not a function`

**To Reproduce**
1. Set up the app normally from a fresh install
2. Configure the app to use nextjs
3. Compile a production build via `yarn build:nextjs`
4. Run the app via `yarn workspace @scaffold-eth/nextjs-app next start`
5. Visiting the browser results in an `Internal Server Error`

**Expected behavior**
App should run normally

**Screenshots**
<img width="782" alt="image" src="https://user-images.githubusercontent.com/26343/216786686-83742a7a-3e0b-41e9-9415-76ee4dea2352.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Chrome
 - Version: 108.0.5359.124
 - Node Version: 18.14.0

**Additional context**
Probably related to: https://github.com/scaffold-eth/eth-ui/issues/172

**Comment by bobRafat** [comment]
I'm having the same issue. @polats did you find a workaround for this problem?

**Comment by polats** [comment]
@bobRafat unfortunately not, there is a newer version of scaffold eth that might be worth looking at instead: https://github.com/scaffold-eth/scaffold-eth-2
