### ISSUE TITLE
Gas showing a ?

### ISSUE THREAD

**Issue by codenamejason** [scaffold-eth/scaffold-eth-typescript#18]
**Describe the bug**
gas is showing a question mark

**To Reproduce**
1. yarn start
2. got to web page

**Expected behavior**
to show the gas price

**Screenshots**
<img width="402" alt="Screen Shot 2021-10-12 at 9 21 12 AM" src="https://user-images.githubusercontent.com/9419140/136964270-5d735cf4-1844-4238-9bca-cbb720669adf.png">

**Additional context**
I am not sure how important it is to show the gas on localhost and local chain...

**Comment by ShravanSunder** [comment]
@codenamejason 
When ethers can't measure the gas, and its not mainnet, and there is no NetworkInfo gas provided for the current network selected, i show '?'.

should we always only show mainnet?  shouldn't we show the current networks gas?  like for example you select matic, it should show matic gas.

**Comment by ShravanSunder** [comment]
@codenamejason  can i close this?
