### ISSUE TITLE
Add auto refresh when you deploy new contracts.

### ISSUE THREAD

**Issue by codenamejason** [scaffold-eth/scaffold-eth-typescript#19]
Add auto refresh when you deploy new contracts, this is a key feature with Scaffold-Eth

**Comment by ShravanSunder** [comment]
@codenamejason can you show recreation steps?  currently auto refresh works for me when you hardhat deploy

**Comment by ShravanSunder** [comment]
@codenamejason  refresh works on deploy, i just tried it.  closing this for now
