### ISSUE TITLE
command not found: mustache

### ISSUE THREAD

**Issue by jellydn** [scaffold-eth/scaffold-eth-typescript#34]
**Describe the bug**

**To Reproduce**
1. Clone repo
2. Run `yarn chain`
3. Run ` yarn deploy-and-graph`

**Expected behavior**
Shouldn't throw error

I guess it need to tell which package/CLI install on this repo or install globally with npm/yarn

**Comment by ShravanSunder** [comment]
not really sure what this command has to do with this repo.  @jellydn  I would like you to to provide a fuller explanation.

**Comment by azf20** [comment]
@jellydn did you run `yarn install` first?

**Comment by ShravanSunder** [comment]
closed due to lack of response
