### ISSUE TITLE
Frontend Deployment: cannot connect wallet in production-bundled app

### ISSUE THREAD

**Issue by dvinubius** [scaffold-eth/scaffold-eth-typescript#55]
After **successfully** running the app **deployed on rinkeby from localhost**, I deploy to surge but can't connect the wallet.

The web3 modal does not open, there are errors in the console:

![Screenshot 2022-01-17 at 03 32 57](https://user-images.githubusercontent.com/32189942/149687634-e5025d89-b91a-4a25-abc5-23fa13ab15ee.png)

What I gather is that the app **tries to retrieve the chainId with a call to localhost:8545**, even though it is configured with the targetNetwork rinkeby:

![Screenshot 2022-01-17 at 03 37 17](https://user-images.githubusercontent.com/32189942/149687786-01a7f057-7825-44c9-abe7-2dcbfbf0cf8e.png)

![Screenshot 2022-01-17 at 03 35 54](https://user-images.githubusercontent.com/32189942/149687705-ddb0b446-3f03-4f15-8519-2d5bcac5889e.png)

**Comment by grothem** [comment]
I think you can only use http from local host. Not sure if there's anything we can do here.

**Comment by dvinubius** [comment]
@grothem There are no explicit http requests in the scaffold-eth project, this is something that happens under the hood.

@ShravanSunder I think this may be also a hooks issue like https://github.com/scaffold-eth/eth-hooks/issues/133

I decided to post it here since it only became visible to me by using scaffold-eth:  I went through the workflow and **deployed the frontend** only then it is an issue. But I suspect it to be from the web3 modal init. 

Will look into it by tomorrow if it's not assigned by then.

**Comment by dvinubius** [comment]
For better context: 


Just made another go with the whole typescript setup out of the box.
Took the last working commit :  0bbf7a4a5dd49c3a359a441e2f86937d8e487ea7

If I deploy the frontend to a **non-https url**, the issue is that the web3 connect modal cannot be opened:

![Screenshot 2022-01-18 at 14 15 35](https://user-images.githubusercontent.com/32189942/149935772-4c678bfa-0af2-43d1-ad4b-5e42baaa04b0.png)

So one clear issue is that "A valid EthersModalConnector was not provided".

If I deploy to a **https url**, additionally the issue detailed earlier can **be observed**.

So there may be actually 2 issues in here, possibly connected. 

What happens here is that **2 of the rpc calls go to localhost when they should not.**
Precisely: one with `method: "net_version"` and one with `method: "eth_chainId"`
This seems to arise from the hooks.


It may be that "EthersModalConnector was not provided" because these calls don't return the values we need, but we'll see as soon as the first one is fixed.

**Comment by dvinubius** [comment]
I've fixed the issue with requests to localhost taking place within the deployment to surge, will PR in a minute.

The issue with "A valid EthersModalConnector was not provided" is still there. It only occurs with a deployment away from localhost.

**Comment by ShravanSunder** [comment]
@dvinubius  thanks for looking into this!  i merged your PR and tested it

**Comment by dvinubius** [comment]
@ShravanSunder Don't know if the label "Good first issue" fits so well here :)

Been digging very deep to find out why it's not possible to open the web3 modal in production.
Seems to me it's an issue due to vite and how the production build is created.

The following applies to the code on the **next** branch. 

First of all, the issue can also be **reproduced locally**

```
yarn build

cd packages/vite-app-ts/dist/assets

python3 -m http.server --cgi 8080
```

When you attempt to open the web3 modal you see this, as described earlier:

![Screenshot 2022-01-22 at 13 34 05](https://user-images.githubusercontent.com/32189942/150636862-4066246d-ca9a-4208-b32c-1d455882d623.png)

The issue is due to a **EthersModalConnector** being **null**.

That happens because the code from `createLoginConnector` in `useScaffoldEthProviders` fails to create it:

![Screenshot 2022-01-22 at 13 43 21](https://user-images.githubusercontent.com/32189942/150637180-13679507-58a7-4a07-ae23-fa58a424666d.png)

That happens because the condition from `if (web3Config)` evaluates to false.

It is false because web3Config is never set:

![Screenshot 2022-01-22 at 13 46 01](https://user-images.githubusercontent.com/32189942/150637246-8571d4a5-aff1-44ad-a518-ff05e142207c.png)

And that is beacuse **the import** of `web3ModalConfig` **fails**.

During the import of `web3ModalConfig` we get this error: 

![Screenshot 2022-01-22 at 02 22 50](https://user-images.githubusercontent.com/32189942/150637276-5d0c1da0-6bf4-4ecb-954f-753acb878ba4.png)

It arises while the code from `web3ModalConfig.ts` attempts to do these imports:

![Screenshot 2022-01-22 at 13 50 53](https://user-images.githubusercontent.com/32189942/150637392-95fa5b79-a5a3-4e0b-976b-0055212c3b59.png)

**Not all of them, but several** (WalletLink and Portis for sure) throw this error from `subscriptionManager. .... .js`.

Since we don't do these imports in a try-catch block, the whole file cannot be used as a module because it always fails to execute.

## Proposed solution 

we do the imports in try-catch blocks and getWeb3ModalConfig returns smth like this:

![Screenshot 2022-01-22 at 13 55 51](https://user-images.githubusercontent.com/32189942/150637581-d3f55f80-eb32-4c05-96bf-1eefd5e733f5.png)

It solves the problem in that users can at least connect with a few of the options, metamask being one of them:

<img src="https://user-images.githubusercontent.com/32189942/150637638-cff7a60d-b13c-4608-a1ba-a1d50abcb293.png" width=400>


## Towards a complete solution

I've tried regular imports in `web3ModalConfig.ts`:

![Screenshot 2022-01-22 at 14 00 41](https://user-images.githubusercontent.com/32189942/150637706-bb839535-f0e1-43ea-a2a2-784fd8d4d737.png)

It gets even worse. The error is now thrown when the code of the MainPage.....js module is first executed, in order to load it. So - no MainPage component to view at all.

![Screenshot 2022-01-22 at 14 02 19](https://user-images.githubusercontent.com/32189942/150637775-25da47f4-9ccd-4aac-9f92-ea5d52ab2dc1.png)

Our only real solution may be to **get in touch with the Vite developer**. I've tried with earlier versions of vite, like 2.6 and 2.5, but the all produce the error similarly.

## Root cause - Vite?

What follows may not be really relevant to us, but I write it up anyway, who knows.

I've found **the place where the error actually arises**. 

Several of these imports require that `subscriptionManager....js`

I wasn't able to identify any project dependency which contains the code, but the issue is because some **node** code is executed:

When using the async imports, the code is a bit cryptic:

![Screenshot 2022-01-22 at 14 19 23](https://user-images.githubusercontent.com/32189942/150638301-627f86b5-1677-4578-bee7-685366d14f8f.png)

But when doing regular imports (and the error is thrown on page load) the code is easier to identify:

![Screenshot 2022-01-22 at 14 14 09](https://user-images.githubusercontent.com/32189942/150638187-1d7170b8-85c8-4fc0-8638-f49374760bab.png)

The code come from the Buffer library (Feross Aboukhadijeh <https://feross.org/opensource>)

It attempts to read `.util` from window. There is no such property on window, and not supposed to be.

However you have `global.util` when you run a node script. 

In the browser, `global` becomes `window`, so `global.util` can't work in the browser because it translates to `window.util`

I think **vite produces this code** when bundling the app for production.

When vite executes the build command it runs a script that requires a file that, for vite@2.7.12, is at ```dist/node/chunks/dep-0351185a.js``` 

In this file there is 

![Screenshot 2022-01-22 at 14 25 01](https://user-images.githubusercontent.com/32189942/150638578-5e701e04-76ab-473a-9d66-533a204e90b0.png)

That import ends up being used, from what I gather, with these functions

![Screenshot 2022-01-22 at 14 26 27](https://user-images.githubusercontent.com/32189942/150638590-885b8856-99b9-4f9a-ac96-5465e90dc9f7.png)

From the comments I'm even more inclined to believe that we're on the right track here.

**Comment by ShravanSunder** [comment]
I am wondering about the behaviour of you turn off the Boolean configs for burner wallet. 
Also removing the burner wallet connector in web3 config. It might be causing issues as it’s only meant for localhost.

**Comment by dvinubius** [comment]
Turning the burner off doesn't help, just tried to make sure

**Comment by dvinubius** [comment]
@ShravanSunder if you're considering removing the connectors, why not try-catch each one of them, like described above? That way at least we would keep as many as possible of the connect options.
That's how I got to 
<img src="https://user-images.githubusercontent.com/32189942/150637638-cff7a60d-b13c-4608-a1ba-a1d50abcb293.png" width=400>

The above is from the production-bundled app

I can make a PR this evening.

**Comment by ShravanSunder** [comment]
Actually the main issue is deeper and related to node /commonjs libs, I think I should fix that first before we look into connectors.  

I do like your connector ideas, however when imports break, try catch will not help you unless its dynamic imports.

**Comment by dvinubius** [comment]
If we can fix it at the root, all the better.

Would the root solution be to convert our web3 connector dependencies from commonjs to es6 right after installing them?
I see @rollup/plugin-commonjs can do that.

I've also found that we do have vite.config.ts set up in order to polyfill some stuff for the browser. But it doesn't seem to address the `util`-related issue.


But our web3 ones are dynamic imports anyway, no?
