### ISSUE TITLE
Update vite config for excluded dependencies

### ISSUE THREAD

**Issue by grothem** [scaffold-eth/scaffold-eth-typescript#57]
`ipfs-http-client` should not be in the list of dependencies that is excluded from eager bundling by vote. See the `vite.config.ts` file:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/23554636/149865808-e846ae6c-cc6b-4c02-b982-785563a38275.png">

Update the `excludeDeps` array and remove `ipfs-http-client`

The app will compile and run as-is, but if you try to use `ipfs-http-client`, it'll cause a runtime error.

**Comment by ShravanSunder** [comment]
- done in https://github.com/scaffold-eth/scaffold-eth-typescript/pull/65
