### ISSUE TITLE
The accounts script does not show the address balance

### ISSUE THREAD

**Issue by grothem** [scaffold-eth/scaffold-eth-typescript#60]
**Describe the bug**
The output of the accounts script always shows 0 for the account balance

**To Reproduce**
1. Generate a deployer account with `yarn generate`
2. Fund it
3. Run `yarn accounts`
4. Look at the output of the command, the balance shows 0

**Expected behavior**
The balance should reflect the actual balance of each network

**Comment by ShravanSunder** [comment]
@grothem  i have a fix for this! will deploy this weekend

**Comment by grothem** [comment]
Sweet, thanks!

**Comment by ShravanSunder** [comment]
fixed in 9d176d5910d8ffcc988bd5b4e589eeacc393b18c  
- #62
