### ISSUE TITLE
Update .gitignore for hardhat generated files

### ISSUE THREAD

**Issue by grothem** [scaffold-eth/scaffold-eth-typescript#63]
When I was updating the challenges with eth-hooks-v4, I noticed that all of my hardhat generated files were being added as modified files in my git changes. 

I think we want to exclude everything in `packages/hardat-ts/generated`

**Comment by ShravanSunder** [comment]
@grothem can you show me a screen shot?  we have generated folder ignored in the next branch

![image](https://user-images.githubusercontent.com/5294949/151288218-a23e781d-e90c-4fb3-b0af-acc46fa348a4.png)

**Comment by grothem** [comment]
Yeah my bad, this can get closed. I must have had a bad merge.
