### ISSUE TITLE
Vite app won't start

### ISSUE THREAD

**Issue by dvinubius** [scaffold-eth/scaffold-eth-typescript#72]
I've performed a clean walkthrough of the getting started steps with the latest from release (0.2.0).

install, chain, contracts:build, deploy, start

Vite-app won't start at all.

Browser just loading with an empty page

Vite output:

![Screenshot 2022-02-12 at 11 34 34](https://user-images.githubusercontent.com/32189942/153706106-5cab5e98-463b-4cbf-bae6-4c069b5b9594.png)

No output at all in the browser console

**Comment by dvinubius** [comment]
Very strange... left it alone for a few hours. When I returned it worked. 

Cannot reproduce anymore.

**Comment by dvinubius** [comment]
Reopening since the issue returned.

On `yarn start` it seems like vite is stuck for ~3 minutes, then it serves the page. 

It doesn't happen to other envs, so it's not like my system is out of memory. I even have another scaffold-eth-ts-env running, but with older code. No problems there

**Comment by joescharf** [comment]
Also seeing this on a fresh fork of this repo. Hasn't resolved 3 minutes per @dvinubius prior comment. See screencap from FF, also tried private window and safari. I'm getting familiarized w/ this repo so am still tracking this one down, but wanted to corroborate this issue.

<img width="1219" alt="Screen Shot 2022-02-21 at 11 51 19" src="https://user-images.githubusercontent.com/43955/155012367-2d994f1e-c6a9-454f-b18e-99df98dd5b77.png">

**Comment by dvinubius** [comment]
@joescharf First times I had the issue it was while keeping 2 vite apps running (I was working on 2 projects in parallel). When I closed the second one the issue was gone.

Later it happened again with only one vite app running, but went away as soon as I would reload the browser page. 

Hope it helps.

**Comment by ShravanSunder** [comment]
@dvinubius i made some changes, let me know if `next` branch is good now

**Comment by joescharf** [comment]
`next` branch is working for me now

**Comment by dvinubius** [comment]
@ShravanSunder thanks, will check it out and let you know
