### ISSUE TITLE
yarn install throws error at "gluegun": remote archive doesn't match the expected checksum

### ISSUE THREAD

**Issue by marty-mcgee** [scaffold-eth/scaffold-eth-typescript#76]
**Describe the bug**
Trying to install this repo using "yarn install", but an error is thrown and no node_modules are installed.

**To Reproduce**
1. cmd> gh repo clone scaffold-eth/scaffold-eth-typescript
2. cmd> yarn install
3. See error: "gluegun@... The remote archive doesn't match the expected checksum"

```
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 320ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:4.8.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zod@npm:3.11.6 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ gluegun@https://github.com/edgeandnode/gluegun.git#commit=b34b9003d7bf556836da41b57ef36eb21570620a can't be
➤ YN0018: │ gluegun@https://github.com/edgeandnode/gluegun.git#commit=b34b9003d7bf556836da41b57ef36eb21570620a: The remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 46s 682ms
➤ YN0000: Failed with errors in 47s 8ms
```

**Expected behavior**
Installation using yarn@3.1.1 should complete without errors and node_modules should be downloaded and built correctly.

**Screenshots**
See attached screenshot.
![scaffold-eth-typescript-yarn-install-error-2022-02-18_7-24-13](https://user-images.githubusercontent.com/693427/154712243-055f4f88-9f52-4705-88cc-8247e74ec7f9.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Terminal: cmd.exe as Administrator
 - Browser: n/a
 - Version: 21H2 (build 22000.527)

**Smartphone (please complete the following information):**
n/a

**Additional context**
Also attempted in Windows PowerShell as a regular user (non-Administrator), but same failure.

**Comment by marty-mcgee** [comment]
I am able to get yarn install to work by making the following change to the root .yarnrc.yml file..
`checksumBehavior: "update"`

See this primary link for more details: 
[yarnrc checksumBehavior](https://yarnpkg.com/configuration/yarnrc#checksumBehavior)
Allowed values are "throw" (default), "update", and "ignore".

..and this supportive link:
[YN0018 - CACHE_CHECKSUM_MISMATCH (YARN_CHECKSUM_BEHAVIOR)](https://yarnpkg.com/advanced/error-codes#yn0018---cache_checksum_mismatch)

My complete .yarnrc.yml code is this:
```
checksumBehavior: "update"
nmHoistingLimits: workspaces
nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
yarnPath: .yarn/releases/yarn-3.1.0.cjs
```

Please also see this related bug/issue: 
[Pull #68 ](https://github.com/scaffold-eth/scaffold-eth-typescript/pull/68)

**Comment by ShravanSunder** [comment]
@companyjuice i've made yarn use checksumBehaviour ignore in the latest `next` branch
