### ISSUE TITLE
http / http-browserify Error

### ISSUE THREAD

**Issue by wadader** [scaffold-eth/scaffold-eth-typescript#94]
Following the steps as described in the Readme, after running: 

```
yarn contracts:build

yarn deploy
```

`yarn start
`
causes an error which says:

` Could not read from file: ...\packages\vite-app-ts\http-browserify`

```
./common/node_modules/request/request.js:3:19:
      3 │ var http = require('http')
```

The readme was followed as is:

OS: Windows 10
IDE: Vscode

**Comment by ShravanSunder** [comment]
@Mbaamir  please share your reproduction.  What version of node are you using?

**Comment by wadader** [comment]
Node v16.4.1
OS: Windows 10

Any more details I can provide?

**Comment by ShravanSunder** [comment]
@Mbaamir A repo branch would be great.   It works on a clean install for me, however i'm using a mac.

**Comment by ShravanSunder** [comment]
probably fixed with the new aliases
